---
- name: Retrieve Login Credentials
  include_vars: /home/temi/EVE/VXLAN/ansible-code/secret.yaml

- name: Define Providers
  set_fact:
  provider:
  host: "{{ ansible_host }}"
  username: "{{ creds['username'] }}"
  password: "{{ creds['password'] }}"


- name: Configure Send Community Both
  nxos_config:
   provider: "{{ provider }}"
   lines:
    - send-community both
  parents: address-family l2vpn evpn
  save_when: always
  
