---
- name: Retrieve Login Credentials
  include_vars: /home/temi/EVE/VXLAN/ansible-code/secret.yaml

- name: Define Providers
  set_fact:
  provider:
  host: "{{ ansible_host }}"
  username: "{{ creds['username'] }}"
  password: "{{ creds['password'] }}"

- name: Configuring Global BGP on Spine Switches
  nxos_bgp:
   provider: "{{ provider }}"
   asn: "{{ bgp_asn }}"
   router_id: "{{ router_id }}"
   state: present
  when: role == "spine"


- name: Config BGP on Spine Switches
  nxos_bgp_neighbor:
   provider: "{{ provider }}"
   asn: "{{ bgp_asn }}"
   neighbor: "{{  leaf_loopback_network }}"
   remote_as: "{{ bgp_asn }}"
   update_source: "{{ loopback0 }}"
   state: present
  when: role == "spine


- name: Configure BGP Address Family on Spine Switches
  nxos_bgp_neighbor_af:
   provider: "{{ provider }}"
   asn: "{{ bgp_asn }}"
   neighbor: "{{  leaf_loopback_network }}"
   afi: l2vpn
   route_reflector_client: true
  when: role == "spine"
