---
- name: Retrieve Login Credentials
  include_vars: /home/temi/EVE/VXLAN/ansible-code/secret.yaml

- name: Define Providers
  set_fact:
  provider:
  host: "{{ ansible_host }}"
  username: "{{ creds['username'] }}"
  password: "{{ creds['password'] }}"


- name: Config BGP on Leaf Switches
  nxos_bgp_neighbor:
   provider: "{{ provider }}"
   asn: "{{ bgp_asn }}"
   router_id: "{{ router_id }}"
   neighbor: "{{  spine01_loopback0 }}"
   remote_as: "{{ bgp_asn }}"
   update_source: "{{ loopback0 }}"
   state: present
   when: role == "leaf"


- name: Configure BGP Address Family on Leaf Switches
  nxos_bgp_neighbor_af:
   provider: "{{ provider }}"
   asn: "{{ bgp_asn }}"
   neighbor: "{{ spine01_loopback0 }}"
   afi: l2vpn
   when: role == "leaf"

- name: Config BGP on Leaf Switches
  nxos_bgp_neighbor:
   provider: "{{ provider }}"
   asn: "{{ bgp_asn }}"
   router_id: "{{ router_id }}"
   neighbor: "{{  spine02_loopback0 }}"
   remote_as: "{{ bgp_asn }}"
   update_source: "{{ loopback0 }}"
   state: present
   when: role == "leaf"


- name: Configure BGP Address Family on Leaf Switches
  nxos_bgp_neighbor_af:
   provider: "{{ provider }}"
   asn: "{{ bgp_asn }}"
   neighbor: "{{ spine02_loopback0 }}"
   afi: l2vpn
   when: role == "leaf"