---
- name: Retrieve Login Credentials
  include_vars: /home/temi/EVE/VXLAN/ansible-code/secret.yaml

- name: Define Providers
  set_fact:
  provider:
  host: "{{ ansible_host }}"
  username: "{{ creds['username'] }}"
  password: "{{ creds['password'] }}"

- name: Enable OSPF instance globally
  nxos_ospf:
    provider: "{{ provider }}"
    ospf: "{{ ospf_instance_id }}"
    state: present

- name: Enable OSPF on loopback interfaces
  with_items: "{{ loopbacks }} "
  nxos_interface_ospf:
   provider: "{{ provider }}"
   interface: "{{ item.interface_name }}"
   ospf: "{{ ospf_instance_id }}"
   area: "{{ ospf_area }}"
    
- name: Enable OSPF on layer3 intefaces 
  with_items: "{{ layer3_interfaces }}"
  nxos_interface_ospf:
   provider: "{{ provider }}"
   interface: "{{ item.interface }}"
   ospf: "{{ ospf_instance_id }}"
   area: "{{ ospf_area }}"

 
  
