---
- name: Retrieve Login Credentials
  include_vars: /home/temi/EVE/VXLAN/ansible-code/secret.yaml

- name: Define Providers
  set_fact:
  provider:
  host: "{{ ansible_host }}"
  username: "{{ creds['username'] }}"
  password: "{{ creds['password'] }}"


- name: Configure Anycast RP on Leaf Switches
  nxos_config:
   provider: "{{ provider }}"
   lines:
    - copy running-config startup-config
