---
hostname: leaf04
mgmt_ip: 192.168.1.134
router_id: 10.10.30.4
role: leaf
loopbacks:
        - interface_name: loopback0
          mode: layer3
          ip_address: 10.10.10.4
          subnet_mask: 32
          interface_type: loopback
          description: "leaf04 loopback0"

        - interface_name: loopback1
          mmode: layer3
          ip_address: 10.10.20.4
          subnet_mask: 32
          interface_type: loopback
          description: "leaf04 loopback1"


layer3_interfaces:
        - interface: Ethernet1/1
          description: Uplink to Spine01

        - interface: Ethernet1/2
          description: Uplink to Spine02


