---
hostname: leaf02
mgmt_ip: 192.168.1.132
router_id: 10.10.30.2
role: leaf
loopback0: 10.10.10.2
loopbacks:
        - interface_name: loopback0
          mode: layer3
          ip_address: 10.10.10.2
          subnet_mask: 32
          interface_type: loopback
          description: "leaf02 loopback0"

        - interface_name: loopback1
          mode: layer3
          ip_address: 10.10.20.2
          subnet_mask: 32
          interface_type: loopback
          description: "leaf02 loopback1"

        - interface_name: loopback2
          mode: layer3
          ip_address: 10.10.30.2
          subnet_mask: 32
          interface_type: loopback
          description: "leaf02 loopback2"

layer3_interfaces:
        - interface: Ethernet1/1
          description: Uplink  to Spine01

        - interface: Ethernet1/2
          description: Uplink to Spine02 
